from gym_pomdps.envs.iterated_prisoners_dilemma import IteratedSelfPD
from gym_pomdps.envs.self_reinforcing_bandit import SelfReinforcingBandit, POMDPBandit
from gym_pomdps.envs.double_tap import DoubleTap
from gym_pomdps.envs.alternating_bandit import AlternatingBandit, MakeActionSpaceDiscrete, MakeObservationSpaceDiscrete
from gym_pomdps.envs.sequential_navigation import SimpleSequentialNav
